version: "3.8"

services:
  db:
    container_name: postgres_db
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
